name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [clang-tidy-gjb8114-updated]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout clang-tidy-gjb8114 Repo at specific SHA
        uses: actions/checkout@v4
        with:
          repository: gjb8114/clang-tidy-gjb8114
          ref: ${{ github.event.client_payload.sha || 'main' }}
          path: ./clang-tidy-gjb8114

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
